PACKAGE_NAME="eoip"
BASEDIR=$(dirname "${BASH_SOURCE[0]}")
PACKAGE_VERSION=$("$BASEDIR"/version.sh)
AUTOINSTALL="yes"
BUILT_MODULE_NAME[0]="eoip"
BUILT_MODULE_NAME[1]="eoipv6"
BUILT_MODULE_LOCATION[0]="unified"
BUILT_MODULE_LOCATION[1]="unified"
DEST_MODULE_LOCATION[0]="/kernel/net/ipv4"
DEST_MODULE_LOCATION[1]="/kernel/net/ipv6"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/unified modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/unified clean"
STRIP[0]="no"
